# Generated by Django 2.2 on 2019-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
