# Generated by Django 2.2 on 2019-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_auto_20190404_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='desc',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
