# Generated by Django 2.2 on 2019-04-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0003_pokemon_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('evolvesFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from_set', to='pokedex_app.Pokemon')),
                ('evolvesInto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to_set', to='pokedex_app.Pokemon')),
            ],
        ),
    ]
